### ISSUE TITLE
Ad's pop up after every restart

### ISSUE THREAD

**Issue by ruppert10** [blokadaorg/blokada#89] opened 2018-01-08 04:55 UTC
Hi when i restart my android mi box android version 6.0 ad's will show up on my apps ( mobdro - terraraum tv ) i have to go to my blokada and stop the app then restart the app for it to block ad's again i am on the latest version of blokada please look into this issue thank you for your time

**Comment by ruppert10** [comment] 2018-01-08 19:39
Also my ttv and mobdro are also up to date this issue will not go away after many times shuting down or unplugging my mi box restarting all three apps and clearing cache on everything the ad's will still pop up

**Comment by Pinguinguy** [comment] 2018-01-21 00:37
Have you enabled start on boot?

**Comment by alleluia20** [comment] 2018-01-25 09:51
I think this is a duplicate of #81, which I submitted some weeks ago.

**Closed** 2018-02-15 12:51 UTC
Labels: duplicate
