### ISSUE TITLE
.be domains blocked

### ISSUE THREAD

**Issue by kennethhaspeel** [blokadaorg/blokada#951] opened 2022-10-28 09:50 UTC
When using Blokada 5, several .be domains seem to be blocked. This is happening on two Xiaomi phones and one Samsung tablet, in Edge, Chrome and Firefox.
Switching from Wifi to 4G results in the same problem.

Even disabling all block lists doesn't help the problem. As soon as the blokada app is activated, the ip adress cannot be found.
I haven't been testing hundreds of website but it seems to be limited to .be websites
Examples:
https://www.hln.be
https://www.gamma.be
https://www.hubo.be
https://www.telenet.be
https://www.proximus.be
https://www.tweakers.be (tweakers.net can be reached)

these result in "server ip adress not found".
As soon as i disable blokada, the websites can be reached. 

App Version : 22.4.1
Device Model: Xiaomi Mi11, Xiaomi Mi8, Samsung Tab A8
OS Version: MIUI 13.0.12 (not sure about the two other devices)

**Comment by richdougherty** [comment] 2022-10-28 22:39
I can confirm none of those sites work for me either. This is with Blokada 5 22.4.1 with any blocklists enabled. They work if I disable all blocklists.

**This is also happening with `.nz` domains**, for example:

* https://www.linz.govt.nz/ - A government website
* https://www.flicks.co.nz/ - A movie review website
* https://rd.nz/ - My website

They works in Blockada if I turn off all blocklists.

When I try these on my computer using the same blocklist, e.g. OISD, it works fine. I've looked in the OISD blocklist rules and there's nothing that looks like it should block these sites.

I've tested these .nz sites in both Blokada 5 22.4.1, and in Blokada 5.21 and they don't work in either.

**Comment by kar** [comment] 2022-10-31 08:09
Very strange. Thanks for reporting this. Looking into this...

**Comment by fatihbabacan92** [comment] 2022-10-31 20:54
This happens also on version 5.20.1.

Perhaps there's an issue with how the blocklists are being loaded? Because this problem never occured before on older version.

**Comment by fatihbabacan92** [comment] 2022-11-08 20:06
> Credits to https://community.blokada.org/t/for-all-who-experience-internet-is-blocked-by-blokada/27549/2 for pointing out that you can simply switch DNS to something else than Cloudflare (the default) as a workaround.

The workaround no longer works.

**Comment by fatihbabacan92** [comment] 2022-11-08 20:08
> Credits to https://community.blokada.org/t/for-all-who-experience-internet-is-blocked-by-blokada/27549/2 for pointing out that you can simply switch DNS to something else than Cloudflare (the default) as a workaround.

The workaround no longer works.

**Comment by kar** [comment] 2022-11-09 09:49
We're working on the fix!

**Comment by richdougherty** [comment] 2022-11-09 18:25
The workaround still seems to work for me, i.e. setting Google as the DNS provider in the 'All networks' setting.

**Comment by kar** [comment] 2022-11-11 10:11
This is fixed in 22.4.14

**Closed by kar** 2022-11-11 10:11 UTC
Labels: type-B, popularity-3
