### ISSUE TITLE
host log - which app made the call?

### ISSUE THREAD

**Issue by 10000hzl** [blokadaorg/blokada#726] opened 2020-06-03 14:38 UTC
It would be nice if the host log could show **which app** made a certain call that has been allowed/blocked. As of now, we only see which call is made but we don't know which app made it.

**Comment by ParmuSingh** [comment] 2020-06-09 12:34
Agreed. Though issue#418 already exists for this. Make sure to search before opening.

https://github.com/blokadaorg/blokada/issues/418

**Comment by ps100000** [comment] 2020-06-18 15:08
Duplicate of #418

**Closed** 2020-06-18 15:07 UTC
