### ISSUE TITLE
[Feature Request] show which app(s) made a blocked request

### ISSUE THREAD

**Issue by khimaros** [blokadaorg/blokada#819] opened 2021-01-02 22:46 UTC
when looking at the list of blocked requests, it would be helpful to know which app made the request. this would help the user identify misbehaving/malware apps and uninstall them completely.

**Comment by peterroth** [comment] 2021-01-03 08:16
Hi,

It is a duplicate of #418.
With newer and newer android versions it seems to be less and less possible, apps can't monitor other apps and their traffic.
Currently the only option is rooting the device and granting permissions.

**Closed by peterroth** 2021-01-03 08:16 UTC
