### ISSUE TITLE
Can't activate Blokada

### ISSUE THREAD

**Issue by Jaheira** [blokadaorg/blokada#348] opened 2019-03-19 20:09 UTC
Hello,

I can't start Blokata. The screen that asks me to allow a VPN connection doesn't react when I press okay, except for a grey text line that asks me to wait, it would activate Blokada. It does react when I press abort. I have exactly the same problem when I acitvete "watchdog", though it got checkmarked as activated. Since a reboot of the phone, the window pops up again and again for me to allow VPN connection for a while.

I have no installed VPN on my smartphone and a restart didn't help. Tried it with and without activated "watchdog".

Blokada is the version 3.7.022000, my phone is an LG G6 LG-H870DS, Android 8.0.0 

Best regards

P.S. congratulations to Blokada, your app got advertised by the German tech magazine C'T. I saw it on Youtube.

**Comment by rpeter85** [comment] 2019-03-20 08:04
Duplicate of #347

**Closed by rpeter85** 2019-03-20 08:04 UTC
