### ISSUE TITLE
When exiting airplane mode Blokada does not intercept ads anymore

### ISSUE THREAD

**Issue by redihokuto** [blokadaorg/blokada#696] opened 2020-05-11 09:13 UTC
### Actual behaviour
Enter airplane mode while blokada is activated and running properly.
Quit airplane mode (by pressing the airplane icon), The system in not connected to Blokada VPN anymore, while Blokada appears switched on. To enable it again: switch it off (main button on its home screen, then on again)

### Expected behaviour
Resume the VPN while quitting from airplane mode

### Configuration
1. Blokada version: 4.5.2
2. Device model: Samsung S7
3. Android version / ROM: 8.0.0 official ROM 

### Questions
2.  How often does this problem happen to you?
Always.

Thanks for your great tool and effort!!!

**Comment by peterroth** [comment] 2020-05-11 09:28
Duplicate of #650

**Closed by peterroth** 2020-05-11 09:28 UTC
Labels: rejected-wontfix
