### ISSUE TITLE
Ddwrt blokada 3.7

### ISSUE THREAD

**Issue by jakeres** [blokadaorg/blokada#334] opened 2019-02-22 04:12 UTC
### Steps to reproduce
1. Firmware: DD-WRT v24-sp2 (03/25/13) std ; dhcp
2. Blokada 3.7
3. DNS does not work most likely. No website may be accessed by DHCP client

With blokada 3.6 - works fine.
### Expected behaviour

Websites should work

### Actual behaviour

All sites blocked

### Configuration
1. Blokada version
3.7

2. Device model
Nokia, as DHCP client

3. Android version / ROM
Pie . 9

### Questions
1. How long have you been using Blokada? 
1 yr

2. How long time ago has the problem started to happen? 
Ver 3.7

3.  How often does this problem happen to you?
Always

**Comment by colbycdev** [comment] 2019-02-22 04:16
Haven't problems been reported with pie? I know some were supposed to be fixed in 3.7, but I'm on Oreo not pie to test

_Sent from my TETRA using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rpeter85** [comment] 2019-02-22 11:35
Hey,
thanks for the report, did you try to turn off the "DNS fallback" option? That was added to ensure to mitigate the issue reported in #284

**Comment by jakeres** [comment] 2019-02-22 12:31
yes, that option was enabled by default.

**Comment by jakeres** [comment] 2019-02-25 11:42
checked the previous comm

**Comment by rpeter85** [comment] 2019-02-25 11:45
In this case, could you please dig into the configuration, what Blokada gets or reports? I would like to assist, but as I don't have a router that runs DDWRT, I'm afraid I can't reproduce it.

**Comment by animeking9901** [comment] 2019-02-25 15:41
I have a ddwrt router. I can see if I can reproduce this on Oreo,if someone can give me a clearer idea of the issue?

**Comment by jakeres** [comment] 2019-02-25 19:56
Ddwrt  v24-sp2 router with default settings - I have just reset it - and blokada 3.7 do not work together on Android 9 - clean install, just reseted the phone.

However blokada 3.6 works fine. 

I'm not sure how should I provide a log.

Thanks.

**Comment by g6094199** [comment] 2019-03-05 15:40
>     1. Firmware: DD-WRT v24-sp2 (03/25/13) std ; dhcp

Plz dont use such outdated DDWRT versions anymore!

Sash

**Closed** 2019-09-26 11:40 UTC
Labels: type-B
