### ISSUE TITLE
I want Support for ipv6 dns resolvers

### ISSUE THREAD

**Issue by Hydrophobefireman** [blokadaorg/blokada#238] opened 2018-08-17 07:20 UTC
allow to use any custom DNS server (say cloudflare), over ipv6(2606:4700:4700::1111 instead of 1.1.1)

**Comment by Mikaela** [comment] 2018-10-13 13:39
Either related to closely or a duplicate of https://github.com/blokadaorg/blokada/issues/94 ?

**Closed** 2019-07-25 14:36 UTC
