### ISSUE TITLE
I want a button to manual generate the Smart List

### ISSUE THREAD

**Issue by jawz101** [blokadaorg/blokada#763] opened 2020-07-28 15:10 UTC
As I understand, the Smart List is processed once a day to look for new potential hits.  It would be nice to have a button to manually generate the Smart List to see if any recent domain names are caught.

Every time I try the feature out I "prime it" by opening up all of my apps and installing a few ad-ridden games just to get the lists to start blocking things.  The next day I have maybe 90 or so entries in the Smart List.  Then I install a new game and suddenly I see its ads.

It would be nice to be able to aggressively train the Smart List and then taper off later.

**Comment by ps100000** [comment] 2020-08-02 21:54
Duplicate of #745

**Closed by ps100000** 2020-08-02 21:54 UTC
Labels: type-F
