### ISSUE TITLE
I want to have ad-hoc or customised timing of Smart List scheme

### ISSUE THREAD

**Issue by H2172** [blokadaorg/blokada#750] opened 2020-07-16 08:58 UTC
According to the current scheme (https://community.blokada.org/t/beta-feature-smart-list/165), the Smart List is updated daily at 4 am. 

It would be nice if this scheme can be altered (to run at a different time) and if there were an option to trigger it manually, for example in cases where devices are turned off at night.

**Comment by ps100000** [comment] 2020-07-25 00:25
Duplicate of #745

**Closed by ps100000** 2020-07-25 00:25 UTC
