### ISSUE TITLE
Add listed hosts accessed, not just blocked

### ISSUE THREAD

**Issue by colbycdev** [blokadaorg/blokada#301] opened 2018-12-11 15:35 UTC
This may help identify hosts that provide ads, but aren't blocked, or if you just want to know what apps are doing behind your back(like sharing your location) 

_Sent from my TETRA using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by rpeter85** [comment] 2018-12-11 15:44
Duplicate of #178

**Closed by rpeter85** 2018-12-11 15:44 UTC
