### ISSUE TITLE
[Feature request] Shoe app(s) that initiated connection to hosts

### ISSUE THREAD

**Issue by hammadfauz** [blokadaorg/blokada#826] opened 2021-01-21 07:13 UTC
If I tap on a log list item (the one that dhows all blicked and allowed requests grouped by host), I see the time of last log, and the number of times a connection to the host was initiated.

I would also like to see in that list, the app(s) that made those connections.

**Comment by peterroth** [comment] 2021-01-21 15:03
Hi,

It is a duplicate of #418.
With newer and newer android versions it seems to be less and less possible, apps can't monitor other apps and their traffic.
Currently the only option is rooting the device and granting permissions.

**Closed by peterroth** 2021-01-21 15:03 UTC
