### ISSUE TITLE
[feature] show locked trackers or allowed in each app

### ISSUE THREAD

**Issue by MakuSensei** [blokadaorg/blokada#478] opened 2019-08-14 14:48 UTC
Hello and greetings from Argentina, I love this app and I use it a lot.
I wanted to ask you if in the apps section you can add a list of trackers and blocked and allowed websites. So you can control what requests per app allow and which not.
Thank you
![Screenshot_20190814-113706](https://user-images.githubusercontent.com/16900914/63030795-4fcad280-be89-11e9-898b-d2e1db6c8659.png)
![Screenshot_20190814-113749](https://user-images.githubusercontent.com/16900914/63030797-50636900-be89-11e9-8dd5-fe0fb8b26b52.png)
![Screenshot_20190814-113652](https://user-images.githubusercontent.com/16900914/63030799-50636900-be89-11e9-9916-95294a458792.png)

### Steps to reproduce
1.
2.
3.

### Configuration
1. Blokada version

2. Device model

3. Android version / ROM

### Questions
1. How long have you been using Blokada? 

2. How long time ago has the problem started to happen? 

3.  How often does this problem happen to you?

**Comment by alexa-v2** [comment] 2019-08-16 14:08
Duplicate of #418

**Closed** 2019-08-16 14:57 UTC
