### ISSUE TITLE
Blokada stops other VPNs when opened

### ISSUE THREAD

**Issue by Ch4t4r** [blokadaorg/blokada#588] opened 2019-11-26 16:39 UTC
# Steps to reproduce
1. Verify Blokada is not active and not in the list of recents (i.e. not in memory)
2. Start any VPN
3. Open Blokada

### Expected behaviour
Blokada opens, the other VPN stays active

### Actual behaviour
The other VPN stops and no VPN is started (not even Blokadas)

### Configuration
1. Blokada version
4.4.4

2. Device model
OnePlus 3T

3. Android version / ROM
OxygenOS, Android 9

**Comment by peterroth** [comment] 2019-11-26 18:18
Blokada uses the VPN API. Because the underlaying operation system (Android) allows only one app to utilise the VPN API, one of them will crash. Expected behaviour.

**Comment by Ch4t4r** [comment] 2019-11-26 18:20
Yeah, but there is no need for Blokada to try to start a VPN if it is opened without clicking on the activate button - especially if it then goes ahead and doesn't even start itself. Karol asked me to create an issue here.

**Comment by mattbxd** [comment] 2019-11-27 18:34
I can confirm this happens to me too. For the past month or so, I've been wondering why both my OpenVPN and WireGuard clients for my self hosted VPN servers would seemingly disconnect randomly. 

It turns out that simply dragging my notification shade down to reveal the Blokada quick tile is enough to trigger the disconnection of the currently running VPN client. I figured it out when I noticed that the quick tile was rapidly changing from "Active" to "Disabled" whenever I pulled the notification shade down even though Blokada itself was not running. 

Samsung Galaxy S10+ running OneUI 1.1. November security patch

**Comment by eladkarako** [comment] 2019-12-24 00:38
This is not a bug, 
you can only have one VPN (proxy) running at a time, 
and Blokada is built like a proxy (even if it is not tunneling the traffic through another IP-server).

You can either use the built-in feature to tunnel traffic (VPN) of Blokada (not free..)
Similar solutions (AdGuard) work in the same way, and also won't allow other VPNs from running.

**Comment by peterroth** [comment] 2019-12-24 04:29
The VPN tunnel shouldn't be claimed at the app start up, only when ad filtering or Blokada Tunnel is activated. However it seems it isn't so, @eladkarako

**Comment by eladkarako** [comment] 2019-12-24 10:03
Thanks @peterroth, 
I can successfully have Blokada working in the background (setting: keep-alive icon - ON, ad-blocking - OFF), while another VPN<sub><a href="https://apkmb.com/?s=vpn">,</a></sub> runs.
As soon as I enable Blokada ad-blocking the <em>little 🔑︎ icon</em> from the previous VPN connection is removed, and after few moments the <em>🔑︎ icon</em> returns (for Blokada) as expected.

as for the reversed order (launching Blokada after another VPN connection has established), 
I haven't been disconnected, until I've activated the Blokada's ad-blocking.

I'm setting Blokada to have "keep alive icon", and "aggressive start", but turned off the "blocking on the start", this way I can quickly switch from Blokada to another VPN by switching ON/OFF Blokada's ad-blocking along (it keeps on running in the background).

Have you tried to make sure the ad-blocking is set to be manually activated?

Ps.
Although on my device <sup>Samsung J400F Android 9</sup>, 
the VPN implementation seems OK (set by demand).

Your device or operation-system version (ver< Android 7), 
might request the VPN exclusively, due to this permission (android manifest):

```xml
        <service android:name="tunnel.Service" android:permission="android.permission.BIND_VPN_SERVICE">
            <intent-filter>
                <action android:name="android.net.VpnService"/>
            </intent-filter>
        </service>
```

As far I can remember binding <code>android.net.VpnService</code> on older versions of Android brings up the VPN dialog everytime, disconnecting the previous connection immediately, 
so it <strong>might</strong> be a difference in implementation in different Android versions.

**Comment by Ch4t4r** [comment] 2019-12-24 10:13
It's kinda hard to read trough your comment as I don't seem to understand how most of it is related.

Binding the VPN service is required to even be able to run a VPN. It does not bring up the dialog automatically, it has to be started from the Intent returned from `VpnService.prepare(context)`.

**Comment by kar** [comment] 2021-03-11 16:04
Fixed in v5

**Closed by kar** 2021-03-11 16:04 UTC
Labels: type-B
