### ISSUE TITLE
Unexpected battery drain, how to debug?

### ISSUE THREAD

**Issue by Kianda** [blokadaorg/blokada#294] opened 2018-11-23 09:53 UTC
### Steps to reproduce
1. Install Blokada
2. Check later battery report (https://imgur.com/oIZ60y2)

### Expected behaviour
Battery impact should be minimal

### Actual behaviour
Huge battery drain

### Configuration
1. Blokada version: v3.6
2. Device model: Google Pixel 2 XL
3. Android version: 9

### Questions
1. How long have you been using Blokada? 
On the Pixel 2 XL for like 7 days (the smartphone is new)

2. How long time ago has the problem started to happen? 
Two days ago

3.  How often does this problem happen to you?
Since two days, every day, tried already uninstalling, rebooting etc...

How can I debug what is causing this? How can I help? It can be that some app is causing Blokada to drain so much battery? It can be the adaptive battery feature?

Thanks!

**Comment by colbycdev** [comment] 2018-11-24 02:13
Is your phone killing it, or a booster app?  If its constantly restarting, that would do it

On Nov 23, 2018 4:53 AM, Kianda <notifications@github.com> wrote:
Steps to reproduce

  1.  Install Blokada
  2.  Check later battery report (https://imgur.com/oIZ60y2)

Expected behaviour

Battery impact should be minimal

Actual behaviour

Huge battery drain

Configuration

  1.  Blokada version: v3.6
  2.  Device model: Google Pixel 2 XL
  3.  Android version: 9

Questions

  1.  How long have you been using Blokada?
On the Pixel 2 XL for like 7 days (the smartphone is new)

  2.  How long time ago has the problem started to happen?
Two days ago

  3.  How often does this problem happen to you?
Since two days, every day, tried already uninstalling, rebooting etc...

How can I debug what is causing this? How can I help? It can be that some app is causing Blokada to drain so much battery?

Thanks!

**Comment by Kianda** [comment] 2018-11-24 16:51
Don't have any booster app, I'm on a brand new Pixel so the crap pre-installed is zero!
I'm trying the "keep alive" advanced option to see if that can solve my issue.
Will report back asap

**Comment by Kianda** [comment] 2018-11-26 14:39
Found this:
> Sometimes you may notice that, according to Android built-in statistics, AdGuard consumes a lot of traffic and/or battery resource.
Both these problems are two sides of the same coin. Since in the process of filtering all the mobile traffic goes through AdGuard, Android decides that it is AdGuard that consumes it all. In reality, of course, it is not true.
Battery and traffic consumption shown in devices statistics do not represent the facts. The thing is, Android attributes all of the WiFi and Mobile traffic to AdGuard, which was in fact consumed by other apps. Due to this, AdGuards real share of total consumed traffic and battery resource increases, and the share of other apps, on the contrary, decreases.

Is this true also for Blokada?

**Comment by colbycdev** [comment] 2018-11-26 14:57
Depending on your ROM, but most likely

On Nov 26, 2018 9:39 AM, Kianda <notifications@github.com> wrote:

Found this:

Sometimes you may notice that, according to Android built-in statistics, AdGuard consumes a lot of traffic and/or battery resource.
Both these problems are two sides of the same coin. Since in the process of filtering all the mobile traffic goes through AdGuard, Android decides that it is AdGuard that consumes it all. In reality, of course, it is not true.
Battery and traffic consumption shown in devices statistics do not represent the facts. The thing is, Android attributes all of the WiFi and Mobile traffic to AdGuard, which was in fact consumed by other apps. Due to this, AdGuards real share of total consumed traffic and battery resource increases, and the share of other apps, on the contrary, decreases.

Is this true also for Blokada?

**Comment by leonida5s** [comment] 2018-11-29 06:52
Same issue on my pixel 2 xl. Think it started draining after Pie update

**Comment by prestige88** [comment] 2018-11-30 03:06
Hi there, I'm also having the same issue.

I'm on Pixel 3 (non-xl), latest update of Pie. 

http://i.imgur.com/EmUZrHg.jpg

Is it supposed to show up with such high usage? It's not running in the background or foreground.

https://imgur.com/NOyzr5b.jpg

I've toggled with optimising and not optimising the app to no avail.

I have my friends/brother that don't show up with such large battery drain, so I don't know why mine does. Is there some setting I'm missing?

Thanks!

**Comment by prestige88** [comment] 2018-12-01 23:04
Hi all, I also realised that the drain only occurs when I'm on 4G. When on wifi, my battery is fine.

Anyone have any ideas?

**Comment by georgesolomos** [comment] 2018-12-03 14:00
I'm seeing the same thing on a Pixel 1 with latest 9.0. I'll try enabling Keep Alive and see how it goes.

**Comment by rpeter85** [comment] 2018-12-05 19:14
@kianda yes, as Blokada works similar as AdGuard.

**Comment by animeking9901** [comment] 2018-12-06 17:07
Agreeing with @rpeter85 in the fact that Android confuses that up. Back when I actually had to watch Blockada for ram and data usage,that I have noticed the same

**Comment by fmilligan** [comment] 2018-12-07 15:12
Android has a bad habit of attributing apps that go through a VPN and the apps usage _as_ the VPN

**Comment by leonida5s** [comment] 2018-12-07 23:48
My battery life is a lot worse with it on, so more than just battery reporting

**Comment by rpeter85** [comment] 2018-12-14 11:11
Is there anything else to clarify or to discuss? If not, can we go ahead and close this thread?

**Closed** 2018-12-17 12:44 UTC
Labels: input-needed
