### ISSUE TITLE
Ad blocking settings crashes Blokada gui

### ISSUE THREAD

**Issue by cm-mc** [blokadaorg/blokada#632] opened 2020-01-21 18:20 UTC
#71 # Steps to reproduce
1. Open settings
2. Open ad blocking
3. Try to open Ad blocking settings

### Expected behaviour
Ad blocking settings open

### Actual behaviour
Blokada app (gui) crashes (remains active in background, though)

### Configuration
1. Blokada version
4.5.1

2. Device model
Samsung Galaxy S9+

3. Android version / ROM
9

### Questions
1. How long have you been using Blokada? 
Years

2. How long time ago has the problem started to happen? 
Months

3.  How often does this problem happen to you?
Everytime

**Comment by peterroth** [comment] 2020-01-21 20:35
Kill the app or restart the phone, try again. I'm pretty sure the device has a glitch.

**Comment by cm-mc** [comment] 2020-01-21 23:17
Not sure what you mean by killing the app or restarting the phone, because it's been happening for months, now (think ever since I updated to v.4), so that's been done countless times, since. Also resetting, reinstalling it (just finished doing it, just in case).
None solved it.

Phone is stock 9, updated to January patch; model is unlocked Brazilian Snapdragon SM-G9650 (ZTO).

**Comment by peterroth** [comment] 2020-01-22 11:25
Do you have any other application or tool that uses VPN? Such things can cause malfunction.

**Comment by cm-mc** [comment] 2020-01-22 17:17
None that I know.

**Comment by peterroth** [comment] 2020-01-23 06:28
Can you check the run log Blokada generates? You can save it in 'About Blokada' - 'Share log'. If you choose the file browser app you use you can save the file in a directory you can access.
You can share that with me on [Telegram](https://go.blokada.org/chat)

**Comment by cm-mc** [comment] 2020-01-23 07:39
I have reports enabled in advanced settings, but when I try to save the `blokada.log` file, it just can't be found, and the link I get when saving it to clipboard (`content://org.blokada.origin.alarm.files/files/blokada.log`), assuming that refers to `local storage/Android/*`, points to an empty folder.

Don't have Telegram,  btw.

**Comment by venetin** [comment] 2020-01-26 15:39
I can confirm that this is happening on Blokada v. 4.5.1. The settings are unaccessible because of the crash. The device is Huawei Mate 20 pro, Android 10 stock official version 180.

**Comment by peterroth** [comment] 2020-01-29 18:52
Can somebody who experiences the crash share a log for analysis? You can find a guide how to save the log [here](https://support.blokada.org/hc/en-us/articles/360011563759-How-to-save-Blokada-s-log-for-analysis). If it can't find the log, kill Blolada, clear it's cache and storage, restart, reproduce and save the log.

**Comment by venetin** [comment] 2020-01-29 23:04
The sad thing is that even after cleaning of the cache the exported log ends on 24.01. The day when I updated the application. It seems that the new version has issues with the loging also.

**Comment by kar** [comment] 2020-01-30 07:19
Log issue is fixed. Anyone experiencing the crash could reach out to hello@blokada.org? I'll send over a preview apk to see if the crash is fixed.

**Comment by cm-mc** [comment] 2020-01-31 07:35
@kar: just sent you an email. Took the liberty to attach the log file.

**Comment by peterroth** [comment] 2020-01-31 07:49
Based on the attached log it seems there are (currently we know about Portugese and Ukrainien/Russian) translations (tags) are malformated and causes the app crash.

**Comment by venetin** [comment] 2020-01-31 07:51
So it seems that it is also valid for Bulgarian since I also experience the crash.

**Comment by cm-mc** [comment] 2020-01-31 09:16
Issue fixed; thanks a lot!

**Comment by peterroth** [comment] 2020-01-31 18:52
Thanks for the feedback.

**Comment by venetin** [comment] 2020-02-05 19:02
The issue is not fixed in 4.5.2.

**Comment by peterroth** [comment] 2020-02-05 19:10
I answered you on Telegram:
> I tried to contact you (pinged here) in which language you experience that, but you didn't answer. We found only one typo in a translation, that's fixed

**Comment by venetin** [comment] 2020-02-05 19:48
Hi,
4 coments up and you will see that I wrote that the issue applies also to Bulgarian. If thatbis the case. I can send you a log if you wish since the log issue is fixed in 4.5.2 and I can export the log.

**Comment by venetin** [comment] 2020-03-03 20:34
Any update on this for Bulgarian language?

**Comment by fokditkak** [comment] 2020-03-11 16:17
Hi,
I've managed to reproduce this issue using both 4.5.1 and 4.5.2 versions with Bulgarian interface.
Here is the [blokada.4.5.2.log](https://github.com/blokadaorg/blokada/files/4319331/blokada.log).

**Comment by fokditkak** [comment] 2020-03-22 05:52
I've compared the files from the Russian and Bulgarian translations. The problematic file in question is [this one](https://github.com/blokadaorg/blokada/blob/master/app/src/main/res/values-bg-rBG/strings_logger.xml) on line 6.
The issue was fixed in 4.5.2 for the RU translation. When compared to 4.5.1 I saw that two spaces were deleted surrounding the "/" character. However the spaces exist in the BG version in both 4.5.2 and 4.5.1.
I am kinda shooting in the dark with this but I think it would resolve the issue if it were `...които са разрешени **и/или** блокирани...`

**Comment by s4pun1s7** [comment] 2020-03-25 00:22
I've located the problem. The file is app/src/main/res/values-bg-rBG/strings_panel.xml, line 34, around column 245. There is an extra "%s". Tested and resolved.

**Closed** 2020-06-30 12:47 UTC
Labels: popularity-1, type-B
