### ISSUE TITLE
No ads being blocked on Android 11 Beta

### ISSUE THREAD

**Issue by Notabas-iC** [blokadaorg/blokada#742] opened 2020-06-25 18:23 UTC
### Actual behaviour
Blokada doesn't block ads. After some time / a system update it blocks ads for a short timeframe (2 to 8 hours).

### Expected behaviour
Blokada blocks ads continuously. 

### Steps to reproduce  
1. Enable Blokada.
2. Clear Cache of apps showing in 
3. Search for ads

### Configuration
1. Blokada version: 4.6.4
2. Device model: Pixel 4 
3. Android version / ROM: Android 11 Beta

Additional information gathered:
https://www.reddit.com/r/blokada/comments/h11fgh/does_it_work_on_android_11/ OP will participate in the issue later.
- private DNS is 'off'
- Host log shows Google and Microsoft requests. Cache of apps is cleared
- Host counter doesn't rise
- persistent on mobile data and WiFi
- VPN key shows, Always-on-VPN enabled or not doesn't make a difference.
- block all connections without VPN disabled
- persisting with DNS Fallback (or third party DNS) enabled / disabled
- Blokada is not being optimized 
- persistent with Alternative DNS answer enabled 
- AdGuard doesn't work either
- DataSaver and Traffic Mode are disabled
- no additional system settings for DNS or Proxy found. 
- **two logs send to hello@blokada.org**

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 
Yes, afterwards it worked for a short time

2.  How often does this problem happen to you?
Since the update to Android 11. Blokada worked two times.

**Comment by Pitel** [comment] 2020-07-03 11:35
I can confirm that. Pixel 3a, Android 11 beta, ads in Chrome.

**Comment by tkterris** [comment] 2020-07-08 17:54
I was having an issue with Blokada (and other VPNs) not working when changing networks, which was resolved with the latest 11 beta version (release 2020-07-08).

**Comment by peterroth** [comment] 2020-11-28 07:25
I'm checking in to ask if Blokada works well on Android 11 now.
The target Android version is still 10, due to the limitations of 11, but it should work well.

**Closed** 2020-12-03 21:38 UTC
Labels: type-C
