### ISSUE TITLE
[feature request] better indication of list's download-process

### ISSUE THREAD

**Issue by eladkarako** [blokadaorg/blokada#606] opened 2019-12-24 00:28 UTC
![Screenshot_20191224-021820_Blokada](https://user-images.githubusercontent.com/415238/71386102-3a627380-25f4-11ea-967a-0d18d2026252.jpg)

I wish there was a better indication of list start/progress/end (and success/fail status), 
when downloading the lists.

You can use the status-bar, or even make use of the native Android-download, 
to download the lists to a cache folder (following whatever process you choose to do afterwards), 
this way a user will have a proper way to know what is the download-progress rate, 
and even to stop/resume/cancel the download.

- https://developer.android.com/reference/android/os/AsyncTask.html
- https://stackoverflow.com/questions/15758856/android-how-to-download-file-from-webserver

**Comment by peterroth** [comment] 2020-01-02 12:18
I think it might be a duplicate of #272

**Closed** 2020-01-10 10:02 UTC
Labels: rejected-duplicate, type-F
