### ISSUE TITLE
Could not start Blokada after changing the setting for location of setting from internal to external memory and rejecting privilage in Android 9

### ISSUE THREAD

**Issue by nam108** [blokadaorg/blokada#610] opened 2020-01-01 07:12 UTC
### Steps to reproduce
1. Go setting, advance, change setting for localization of setting
2. Don't give privilege if asked by the system
3. Close the app
4.Turn on the app again
5. It doesn't start.

### Expected behaviour

Should work

### Actual behaviour

After closing the app, it won't start. Only the logo screen for few sec and then disappear.

### Configuration
1. Blokada version
4.4.3

2. Device model
Xiaomi Redmi 7A

3. Android version / ROM
9/MIUI 10

### Questions
1. How long have you been using Blokada? 
1 month

2. How long time ago has the problem started to happen? 
Now

3.  How often does this problem happen to you?
Always, restart doesn't help, only either going Android settings and giving privileges or resting the settings there.

4. Solution
I guess add code for checking after changing mentioned setting if whether the privilege was given finally and if not, change setting back to previous.

**Comment by peterroth** [comment] 2020-01-01 10:41
Duplicate of #600

**Closed by peterroth** 2020-01-01 10:41 UTC
