### ISSUE TITLE
Sometimes Blokada stops blocking when my phone switches from WiFi to cellular

### ISSUE THREAD

**Issue by StarTrekRocks73** [blokadaorg/blokada#192] opened 2018-04-22 18:58 UTC
### Steps to reproduce
Note: This only happens sometimes
1. Enable Blokada blocking with Keep Alive on and Online Only on
2. Exit Blokada
3. Switch between WiFi and cellular.
4. Wait for a moment when Blokada should be blocking a host. (An easy way to test it is by making a phone call using the Google Phone app and waiting for a connection to *.google-analytics.com)
5. Notice that Blokada doesn't block the host.

### Expected behaviour

I expect Blokada to block hosts after switching between WiFi and cellular networks.

### Actual behaviour

Blokada doesn't block hosts after switching between WiFi and cellular networks.

### Temporary solution
This issue can be circumvented by turning off the 'Online Only' feature or toggling the activate button on the Blokada home screen.

### Configuration
1. Blokada version
Version 3.3

2. Device model
Google Pixel (Verizon)

3. Android version / ROM
Android Nougat

### Questions
1. How long have you been using Blokada? 
I have been using it for a few days.

2. How long time ago has the problem started to happen? 
I first noticed the problem on my first day of using Blokada.

3.  How often does this problem happen to you?
It happens sometimes when I switch between WiFi and cellular networks.

**Comment by StarTrekRocks73** [comment] 2018-04-25 12:45
This one has been bothering me. It also happens on my tablet.

**Comment by kar** [comment] 2018-04-25 20:40
Online only, by design, makes the blocking work *only* when device is *online*. I suspect during the network switching there's a brief moment when it's not online, hence vpn gets turned off for a short time, and the tracking/ad gets through. As you noticed turning off online only changes this behavior, it's one of the reasons why this switch exists. Not a bug, unless you can argue otherwise?

**Comment by DMSledge** [comment] 2018-06-12 01:22
I have noticed that sometimes it stays off until I go into the blokada and turn it back on.

**Comment by rpeter85** [comment] 2018-10-12 15:09
Hi,
Could you test the same behaviour with the version 3.6 and let us know if you still face the same issue? Thanks in advance.

**Comment by DMSledge** [comment] 2018-10-15 15:21
Well that went poorly. Enabling online only broke my internet after connecting to a new WiFi network.

**Comment by kar** [comment] 2018-10-16 10:16
Please retry with the today's release (you'll get an update notification). If watchdog still doesn't work, just leave it off. It's being retired for most cases.

**Comment by rpeter85** [comment] 2018-11-15 16:27
No further information provided, I close this ticket.

**Closed by rpeter85** 2018-11-15 16:27 UTC
Labels: input-needed
