### ISSUE TITLE
Not blocking ads any longer in terraraum tv

### ISSUE THREAD

**Issue by ruppert10** [blokadaorg/blokada#138] opened 2018-03-13 12:35 UTC
### Steps to reproduce
1.turn on or off keep alive makes no diffrence you will still get ads
2.
3.

### Expected behaviour
 

in terraraum tv it will block ads on the bottom of the screen but you will get ads EVERY time  a show or a movie ends
shocontent://media/external/file/248844

### Configuration
1. Blokada version

Version 3.0.0

2. Device model

mi box

3. Android version / ROM

Android 6.0

### Questions
1. How long have you been using Blokada? 

4 months

2. How long time ago has the problem started to happen? 

Since the latest updated version of terraraum tv 
( i'm on the latest version 1.9.4 ) and the latest version of blokada. 3.0.0

3.  How often does this problem happen to you?

EVRY time a film or tv show ends

Hi also the same problem on a older version of blokada 2.2.3 ads will pop up at the end of watching anything

Things i tried to fix this are

Step 1. force stop and clear cache on both blokada and terraraum tv restart my mi box then start up blokada again waiting a few minutes to let it fully start up again then open up terraraum tv and play something like i said no ads on the lower part of the screen BUT ads always pop up after watching anything on two diffrent versions of blokada
both versions 

( 2.2.3 and 3.0.0 )

Step 2. restart my mi box and wait for blokada to turn on with the keep alive setting turned on issue still happens 

Issue will still happen even if i turn off keep alive and restart everything and use my remote to turn on blokada

Step 3. i cleared data on both apps and uninstalled and reinstalled both blokada and terraraum tv

Step 4. this i thought for sure would fix it but did not help 

I went into the blacklist and Added the other list the hiphosts ads host file that blocks even more ads

 i forced stoped again and cleared cache on both blokada and terraraum tv and restarted my mi box again i tried diffrent settings of keep alive on i still had the ads pop up i then tried it again with keep alive off and still got the ads poping up. After watching anything i will keep both the unified host file and the hiphosts file in the blacklist but it is making no diffrece with the extra hiphosts ads file in my blacklist the darn ads keep poping up ?? Any other ideas im out of ideas thanks for any help on this it us driving me crazy 😣😣

**Comment by ruppert10** [comment] 2018-03-13 12:49
I also have start on boot turned on no diffrence still getting ads

**Comment by w4tadrag** [comment] 2018-03-14 00:07
Hi there, 

I also use terraraum tv on my Oneplus One, **but I am not seeing any ads,** unless Blokada is off. I am using the Blokada ver. 3.0. I have the default filters on.

**Comment by w4tadrag** [comment] 2018-03-14 00:37
Also which video player are you using? I use VLC player

**Comment by ruppert10** [comment] 2018-03-14 06:39
It will show ads in mx player and yes player vlc player is no good on it has to much audio offset issues for me

**Comment by ruppert10** [comment] 2018-03-16 11:20
Hi guys any other tricks i can try to fix this issue is anyone else on here having the same problem as i am another person in a terraraum help group i am on us also having the same issue as i am is there a certain url i can add to block the ads ?? it is a yatse add or a dominos gambling add that pop up most of the time that i keep getting thanks for any help

**Comment by alexanderadam** [comment] 2018-03-20 09:02
Seems to be a duplicate of #137.

**Comment by kar** [comment] 2018-04-07 06:26
This should work on 3.2+ and adzhosts.

**Closed by kar** 2018-04-07 06:26 UTC
