### ISSUE TITLE
VPN causes boot issues on Sony Smart TVs

### ISSUE THREAD

**Issue by peterroth** [blokadaorg/blokada#134] opened 2018-03-09 17:21 UTC
If the VPN service is started on boot, the TV won't go to sleep because Blokada runs in the background and won't let the TV start up. The same happens with every other VPN service.
A solution can be that the app stops before the TV turns off and start when the system is up and running.

**Comment by nikolago** [comment] 2019-06-06 07:29
I successfully installed and ran Blokada 3.7 on a Sony TV running Oreo 8.0 Android.

Enabled Blokada, and for the short time it ran, it looks like its worked as intended (I saw I few hosts being blocked in the meantime, which is evident in the log):
```
06-05 22:12:01.892 V b3:tunnel:start       starting vpn   <--   Thread[tunnel-ctrl,5,main]
06-05 22:12:01.911 V b3:tunnel:start       asking system for vpn   <--   Thread[tunnel-ctrl,5,main]
06-05 22:12:02.007 V b3:tunnel:start       vpn established   <--   Thread[tunnel-ctrl,5,main]
06-05 22:12:02.009 V b3:tunnel:start       event:subscriber:on   <--   BLOCKED, Function1<java.lang.String, kotlin.Unit>, Thread[tunnel-ctrl,5,main]
06-05 22:12:02.011 V b3:tunnel:start       vpn started   <--   Thread[tunnel-ctrl,5,main]
06-05 22:12:02.015 V b3:tunnel:start       tunnel thread started   <--   Thread[tunnel-0,5,main], Thread[tunnel-ctrl,5,main]
06-05 22:12:02.016 V b3:tunnel:start       running tunnel thread   <--   tunnel.Tunnel@6249bfd, Thread[tunnel-0,5,main]
06-05 22:12:02.491 V b3:device:connectivity       connectivity receiver ping   <--   Thread[ConnectivityReceiver-worker-2,5,main]
06-05 22:12:02.496 V b3:device       connected   <--   true, Thread[gscore-workerX-4,5,main]
06-05 22:12:02.588 V b3:dns:changed       setup tunnel, start = false, enabled = true   <--   [/192.168.1.1:53], Thread[tunnel-ctrl,5,main]
06-05 22:12:02.636 V b3:dns:changed       unchanged dns servers, ignoring   <--   Thread[tunnel-ctrl,5,main]
06-05 22:12:17.021 V b3:tunnel:legacy       tunnel stable   <--   Thread[retry-worker-1,5,main]
06-05 22:23:59.616 V b3:tunnel:start       event:emit   <--   BLOCKED, googleads.g.doubleclick.net, Thread[tunnel-0,5,main]
06-05 22:25:59.221 V b3:tunnel:start       event:emit   <--   BLOCKED, googleads.g.doubleclick.net, Thread[tunnel-0,5,main]
06-05 22:27:59.483 V b3:tunnel:start       event:emit   <--   BLOCKED, googleads.g.doubleclick.net, Thread[tunnel-0,5,main]
06-05 22:42:35.378 V b3:tunnel:start       event:emit   <--   BLOCKED, securepubads.g.doubleclick.net, Thread[tunnel-0,5,main]
06-05 22:42:36.796 V b3:tunnel:start       event:emit   <--   BLOCKED, googleads.g.doubleclick.net, Thread[tunnel-0,5,main]
06-05 22:42:50.865 V b3:tunnel:start       event:emit   <--   BLOCKED, googleads.g.doubleclick.net, Thread[tunnel-0,5,main]
06-05 22:44:04.115 V b3:tunnel:start       event:emit   <--   BLOCKED, code.getmdl.io, Thread[tunnel-0,5,main]
06-05 22:44:09.713 V b3:tunnel:start       event:emit   <--   BLOCKED, code.getmdl.io, Thread[tunnel-0,5,main]
```

Turning the TV off and then on resulted in Android OS being rebooted (Android TV logo appears before booting up to Home screen).

Attached is a log of the above process, which hopefully can give some insight into the issue.
[blokada.log](https://github.com/blokadaorg/blokada/files/3260422/blokada.log)
Please let me know if I can help out with more information.

**Comment by kar** [comment] 2019-10-10 14:57
Reproducible on 4.3.5?

**Comment by nikolago** [comment] 2019-10-11 06:50
I will give my best to try this out this weekend and provide feedback.

**Comment by alcestneige** [comment] 2019-11-17 22:27
Same problem,last version,all disabled just add filter enabled and the tv does not want to start,then it reboots somehow and its working until it turn it off again.

**Comment by emcepl** [comment] 2020-04-23 19:00
This seems to be a software issue at the Sony's side and seems to be fixed in the recent firmware update: https://community.sony.co.uk/t5/android-tv/bug-android-6-0-1-reboots-after-enabling-vpn-apps/td-p/2284371/page/15

**Closed** 2023-09-07 19:24 UTC
Labels: complexity-1, type-B
