### ISSUE TITLE
Service/app name and its payload in the host log

### ISSUE THREAD

**Issue by kishanhathiwala** [blokadaorg/blokada#812] opened 2020-12-24 00:33 UTC
Hello,

It's a great app. Currently I am using this app in POCO F1. 

It would be helpful if we could see the app name/service name in the host log that is making requests as well as if we could see the payload in those requests.

Thanks, 
K

**Comment by peterroth** [comment] 2020-12-24 17:12
Hi,

It is a duplicate of #418.
With newer and newer android versions it seems to be less and less possible, apps can't monitor other apps and their traffic.
Currently the only option is rooting the device and granting permissions.

**Closed by peterroth** 2020-12-24 17:12 UTC
